export const ActionTypes = {
  UP_VOTE: 'UP_VOTE',
  DOWN_VOTE: 'DOWN_VOTE',
  MODAL_OPEN: 'MODAL_OPEN',
  REMOVE_LINK: 'REMOVE_LINK',
  FORM_SUBMIT: 'FORM_SUBMIT',
  CLEAR_STATE: 'CLEAR_STATE',
  SELECT_SORT: 'SELECT_SORT',
  MODAL_RESET: 'MODAL_RESET',
  PAGINATION_SET: 'PAGINATION_SET',
};
